In [2]:
import torch
import numpy as np

In [3]:
# create tensor from list
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

# create tensor from numpy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
# create one-tensor from another
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

# create random-tensor from another
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2173, 0.8217],
        [0.5128, 0.4356]]) 



In [5]:
# create variation tensor from shape
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Zeros Tensor : \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.8888, 0.8656, 0.4499],
        [0.3560, 0.6622, 0.4693]]) 

Random Tensor: 
 tensor([[0.8888, 0.8656, 0.4499],
        [0.3560, 0.6622, 0.4693]]) 

Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [6]:
# create random tensor from shape
# tensor2 = torch.rand((3,4)) is same as tensor
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device} \n")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu 



In [7]:
# move cpu -> gpu
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [8]:
# tensor slicing
tensor = [[1, 2, 5, 8], 
        [2, 3, 6, 9], 
        [3, 4, 7, 10],
        [4, 5, 8, 11]]
tensor = torch.tensor(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[..., 1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1, 2, 5, 8])
First column: tensor([1, 2, 3, 4])
Last column: tensor([2, 3, 4, 5])
tensor([[ 1,  0,  5,  8],
        [ 2,  0,  6,  9],
        [ 3,  0,  7, 10],
        [ 4,  0,  8, 11]])


In [9]:
# torch concatenate
t = torch.cat([tensor, tensor, tensor], dim=1)
print(t)

tensor([[ 1,  0,  5,  8,  1,  0,  5,  8,  1,  0,  5,  8],
        [ 2,  0,  6,  9,  2,  0,  6,  9,  2,  0,  6,  9],
        [ 3,  0,  7, 10,  3,  0,  7, 10,  3,  0,  7, 10],
        [ 4,  0,  8, 11,  4,  0,  8, 11,  4,  0,  8, 11]])


In [10]:
# matmul vs mul
# y1 == y2 == y3
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.zeros_like(y1)
torch.matmul(tensor, tensor.T, out = y3)
print(y1)

# z1 == z2 == z3
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.zeros_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(z1)

tensor([[ 90, 104, 118, 132],
        [104, 121, 138, 155],
        [118, 138, 158, 178],
        [132, 155, 178, 201]])
tensor([[  1,   0,  25,  64],
        [  4,   0,  36,  81],
        [  9,   0,  49, 100],
        [ 16,   0,  64, 121]])


In [11]:
# tensor sum
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

74 <class 'int'>


In [12]:
# tensor call in-place
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[ 1,  0,  5,  8],
        [ 2,  0,  6,  9],
        [ 3,  0,  7, 10],
        [ 4,  0,  8, 11]]) 

tensor([[ 6,  5, 10, 13],
        [ 7,  5, 11, 14],
        [ 8,  5, 12, 15],
        [ 9,  5, 13, 16]])


In [13]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [14]:
n = np.ones(5)
t = torch.from_numpy(n)

In [15]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
